[template.environment]
  NETLIFY_ACCESS_KEY = "Your Netlify Access Token"
  SITE_TITLE = "Your Site Title"
  SITE_URL = "The URL of your site (without a trailing slash!)"
  SITE_DESCRIPTION = "Your Site Description"